# Generated by Django 5.2.7 on 2025-10-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='hr_zone_cardio_max_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='hr_zone_cardio_min_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='hr_zone_fat_burn_max_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='hr_zone_fat_burn_min_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='hr_zone_peak_max_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='hr_zone_peak_min_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitbituser',
            name='granted_scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
