# Generated by Django 5.2.7 on 2025-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0003_fitbituser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntradayCalories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_user_id', models.CharField(db_index=True, max_length=255)),
                ('datetime', models.DateTimeField()),
                ('calories', models.FloatField()),
                ('level', models.IntegerField(blank=True, null=True)),
                ('mets', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intraday_calories',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['fitbit_user_id', '-datetime'], name='intraday_ca_fitbit__e863ae_idx')],
                'unique_together': {('fitbit_user_id', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='IntradayHeartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_user_id', models.CharField(db_index=True, max_length=255)),
                ('datetime', models.DateTimeField()),
                ('heart_rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intraday_heart_rate',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['fitbit_user_id', '-datetime'], name='intraday_he_fitbit__ae6745_idx')],
                'unique_together': {('fitbit_user_id', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='IntradaySteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_user_id', models.CharField(db_index=True, max_length=255)),
                ('datetime', models.DateTimeField()),
                ('steps', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intraday_steps',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['fitbit_user_id', '-datetime'], name='intraday_st_fitbit__45cba9_idx')],
                'unique_together': {('fitbit_user_id', 'datetime')},
            },
        ),
    ]
