# Generated by Django 5.2.7 on 2025-10-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0004_intradaycalories_intradayheartrate_intradaysteps'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntradayDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_user_id', models.CharField(db_index=True, max_length=255)),
                ('datetime', models.DateTimeField()),
                ('distance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intraday_distance',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['fitbit_user_id', '-datetime'], name='intraday_di_fitbit__42df04_idx')],
                'unique_together': {('fitbit_user_id', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='IntradayElevation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_user_id', models.CharField(db_index=True, max_length=255)),
                ('datetime', models.DateTimeField()),
                ('elevation', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intraday_elevation',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['fitbit_user_id', '-datetime'], name='intraday_el_fitbit__d5d1a2_idx')],
                'unique_together': {('fitbit_user_id', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='IntradayFloors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_user_id', models.CharField(db_index=True, max_length=255)),
                ('datetime', models.DateTimeField()),
                ('floors', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intraday_floors',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['fitbit_user_id', '-datetime'], name='intraday_fl_fitbit__58af62_idx')],
                'unique_together': {('fitbit_user_id', 'datetime')},
            },
        ),
    ]
