# Generated by Django 5.2.7 on 2025-10-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0005_intradaydistance_intradayelevation_intradayfloors'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_user_id', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField()),
                ('breathing_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'breathing_rates',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['fitbit_user_id', '-date'], name='breathing_r_fitbit__5b5ca6_idx')],
                'unique_together': {('fitbit_user_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='IntradayHRV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_user_id', models.CharField(db_index=True, max_length=255)),
                ('datetime', models.DateTimeField()),
                ('rmssd', models.FloatField()),
                ('coverage', models.FloatField(blank=True, null=True)),
                ('hf', models.FloatField(blank=True, null=True)),
                ('lf', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intraday_hrv',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['fitbit_user_id', '-datetime'], name='intraday_hr_fitbit__169e39_idx')],
                'unique_together': {('fitbit_user_id', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='IntradaySpO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_user_id', models.CharField(db_index=True, max_length=255)),
                ('datetime', models.DateTimeField()),
                ('spo2', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intraday_spo2',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['fitbit_user_id', '-datetime'], name='intraday_sp_fitbit__f1c63a_idx')],
                'unique_together': {('fitbit_user_id', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='SkinTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_user_id', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField()),
                ('relative_temp', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'skin_temperatures',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['fitbit_user_id', '-date'], name='skin_temper_fitbit__d1649b_idx')],
                'unique_together': {('fitbit_user_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitbit_user_id', models.CharField(db_index=True, max_length=255)),
                ('log_id', models.BigIntegerField(unique=True)),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('minutes_asleep', models.IntegerField()),
                ('minutes_awake', models.IntegerField()),
                ('minutes_deep', models.IntegerField(blank=True, null=True)),
                ('minutes_light', models.IntegerField(blank=True, null=True)),
                ('minutes_rem', models.IntegerField(blank=True, null=True)),
                ('minutes_wake', models.IntegerField(blank=True, null=True)),
                ('efficiency', models.IntegerField(blank=True, null=True)),
                ('sleep_score', models.IntegerField(blank=True, null=True)),
                ('is_main_sleep', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sleep_logs',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['fitbit_user_id', '-date'], name='sleep_logs_fitbit__278bd2_idx')],
            },
        ),
    ]
