# Generated by Django 5.2.7 on 2025-11-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0006_breathingrate_intradayhrv_intradayspo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbituser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitbituser',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fitbituser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitbituser',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fitbituser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fitbituser',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fitbituser',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitbituser',
            name='member_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitbituser',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
