# Generated by Django 5.2.7 on 2025-11-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0007_fitbituser_age_fitbituser_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbituser',
            name='profile_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
