# Generated by Django 5.2.7 on 2025-11-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0008_fitbituser_profile_synced_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitUserManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fitbit_user_id', models.CharField(db_index=True, max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('member_since', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fitbit_users_m',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fitbit_user_id', '-created_at'], name='fitbit_user_fitbit__3f8dc8_idx')],
            },
        ),
    ]
