# Generated by Django 5.2.7 on 2025-12-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0009_fitbitusermanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolarHeartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('hr', models.IntegerField()),
                ('rr', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'polar_heart_rate',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['device_id', '-datetime'], name='polar_heart_device__d61514_idx'), models.Index(fields=['-datetime'], name='polar_heart_datetim_f8366f_idx')],
            },
        ),
    ]
