# Generated by Django 5.2.7 on 2025-12-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0011_mobileuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileuser',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileuser',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
