# Generated by Django 5.2.7 on 2025-12-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0012_mobileuser_age_mobileuser_height_mobileuser_weight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobileUser',
            new_name='PolarUser',
        ),
        migrations.AlterModelTable(
            name='polaruser',
            table='polar_users',
        ),
    ]
