# Generated by Django 5.2.7 on 2025-12-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0013_rename_mobileuser_polaruser_alter_polaruser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='polarheartrate',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polarheartrate',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='PolarHeartRateNN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('hr', models.IntegerField()),
                ('rr', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_outlier_removed', models.BooleanField(default=False)),
                ('original_hr', models.IntegerField(blank=True, null=True)),
                ('original_rr', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'polar_heart_rate_nn',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['device_id', '-datetime'], name='polar_heart_device__c7e0a0_idx'), models.Index(fields=['-datetime'], name='polar_heart_datetim_af94b6_idx'), models.Index(fields=['username', 'date_of_birth', '-datetime'], name='polar_heart_usernam_eac968_idx')],
            },
        ),
    ]
