# Generated by Django 5.2.7 on 2025-12-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0014_polarheartrate_date_of_birth_polarheartrate_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolarHeartRateIndex5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('date_of_birth', models.DateField(db_index=True)),
                ('datetime_start', models.DateTimeField(db_index=True)),
                ('datetime_end', models.DateTimeField()),
                ('rmssd', models.FloatField(blank=True, null=True)),
                ('sdnn', models.FloatField(blank=True, null=True)),
                ('hf_power', models.FloatField(blank=True, null=True)),
                ('lf_power', models.FloatField(blank=True, null=True)),
                ('lf_hf_ratio', models.FloatField(blank=True, null=True)),
                ('mean_hr', models.FloatField(blank=True, null=True)),
                ('sd_hr', models.FloatField(blank=True, null=True)),
                ('hr_upper', models.FloatField(blank=True, null=True)),
                ('hr_lower', models.FloatField(blank=True, null=True)),
                ('mean_rr', models.FloatField(blank=True, null=True)),
                ('data_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'polar_heart_rate_index_5',
                'ordering': ['-datetime_start'],
                'indexes': [models.Index(fields=['username', 'date_of_birth', '-datetime_start'], name='polar_heart_usernam_e46821_idx'), models.Index(fields=['-datetime_start'], name='polar_heart_datetim_f55850_idx')],
                'unique_together': {('username', 'date_of_birth', 'datetime_start')},
            },
        ),
    ]
